# Bus Simulation Configuration File
# This file contains the configuration settings for the bus simulation.
simulation_time: 160.0
arrival_mean: 2.0
inspection_min: 0.25
inspection_max: 1.05
repair_probability: 0.3
repair_min: 2.1
repair_max: 4.5
num_inspectors: 1
num_repair_stations: 2
seed: 42
output_dir: "results/bus"  # Directory to save results and reports