# Projectile Motion Simulation Configuration

# Initial conditions
x0: 0.0            # Initial x position (m)
z0: 0.0            # Initial z position (m)
vx0: 50.0          # Initial x velocity (m/s)
vz0: 50.0          # Initial z velocity (m/s)

# Physical parameters
mass: 1.0          # Mass of projectile (kg)
air_resistance: 0.01  # Air resistance coefficient
gravity: 9.81      # Gravitational acceleration (m/s²)

# Simulation parameters
dt: 0.01           # Time step (s)
t_final: 10.0      # Final simulation time (s)
method: "both"     # Simulation method: "euler", "rk4", or "both"

# Output directory
output_dir: "results/projectile"